### ISSUE TITLE
Relation to -dash.el?

### ISSUE THREAD

**Issue by swsnr** [rolandwalker/list-utils#1]
Are you aware of [dash.el](https://github.com/magnars/dash.el)?  I has become more or less a de facto standard library in the Emacs Lisp community, as it covers a wide range of list processing needs.

Did you think about contributing your functions to this library?

**Comment by rolandwalker** [comment]
dash.el is probably smarter. I have a local codebase which predates it by some years -- I'm trying to extract libraries from that codebase and publish them in some stable and useful form, and I have various other bits which depend on these particular functions.
If anything here would be useful in dash.el, I am open to suggestions and happy to contribute.
