### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by pkkm** [rolandwalker/list-utils#10]
The latest release of this package, v0.4.6, fails on Emacs 28 due to the problem described in https://github.com/rolandwalker/list-utils/issues/7. The problem is fixed on master, but there hasn't been a release since. Would you mind cutting a new release so that MELPA Stable picks up the fix?

**Comment by rolandwalker** [comment]
Easy - done!

**Comment by pkkm** [comment]
Thanks! I can confirm that MELPA Stable has picked it up and it installs correctly on Emacs 28.
