### ISSUE TITLE
Dependent on cl

### ISSUE THREAD

**Issue by enikko** [rolandwalker/list-utils#6]
LIne 259 has `(require 'cl)` and package `cl` was deprecated in Emacs 27. Would be lovely if this dependency could be removed.

**Comment by rolandwalker** [comment]
Hi!

Yes.  That part was missed in #5.  But I'm hung up on the fact that `cl-defstruct` changes to producing `#s` records in Emacs 27:

 * https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Record-Functions

which breaks many tests.  When called the current way, some compatibility code is apparently used:

 * https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Backward-Compatibility

There are some other broken tests, too!  I guess the tests need to be revised, and separated into a different path for 27+.

**Comment by Dapuva76** [comment]
I upgraded to emacs 28, got curious about that cl error and found that this package is the culprit. I changed all instances of cl to cl-lib, but will this ever get a official fix?

**Comment by rolandwalker** [comment]
Yes, thanks, I would love to fix this.

**Comment by buhtz** [comment]
I confirm this also happens in Emacs 29 (pre-release).

Are there plans for a fix? I'm not a Lisp person. So sorry I can't jump in.
